exclude = [
  "reddit\\.com",
  "medium\\.com",
  "neurobiber",
  "arxiv\\.org",
  "qimao\\.com",
  "xs91\\.net",
  "claudemagazine\\.com",
  "360doc\\.com",
  "csdn\\.net",
  "jyacg\\.com",
  "oreateai\\.com",
  "zhihu\\.com"
]
