#!/usr/bin/env bash
#
# Compare two archived regression runs (M3).
#
# Usage:
#   compare-regression-runs.sh <run_dir_a> <run_dir_b> [--out <delta.json>]
#
# Output:
#   stdout JSON (exit 0 on success)
#
# Exit codes:
#   0 = success (valid JSON emitted to stdout)
#   1 = validation failure (bad args, missing files, invalid JSON)
#   2 = script exception (unexpected runtime error)

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  compare-regression-runs.sh <run_dir_a> <run_dir_b> [--out <delta.json>]

Notes:
  - Expects each run dir to contain summary.json (generated by scripts/run-regression.sh).
EOF
}

out_path=""

if [ "$#" -lt 2 ]; then
  usage
  exit 1
fi

run_a="$1"
run_b="$2"
shift 2

while [ "$#" -gt 0 ]; do
  case "$1" in
    --out)
      [ "$#" -ge 2 ] || { echo "compare-regression-runs.sh: error: --out requires a value" >&2; exit 1; }
      out_path="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "compare-regression-runs.sh: unknown arg: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [ ! -d "$run_a" ]; then
  echo "compare-regression-runs.sh: run_dir_a not found: $run_a" >&2
  exit 1
fi
if [ ! -d "$run_b" ]; then
  echo "compare-regression-runs.sh: run_dir_b not found: $run_b" >&2
  exit 1
fi

summary_a="$run_a/summary.json"
summary_b="$run_b/summary.json"

if [ ! -f "$summary_a" ]; then
  echo "compare-regression-runs.sh: missing summary.json: $summary_a" >&2
  exit 1
fi
if [ ! -f "$summary_b" ]; then
  echo "compare-regression-runs.sh: missing summary.json: $summary_b" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_VENV_PY="${SCRIPT_DIR}/../.venv/bin/python3"
if [ -x "$_VENV_PY" ]; then
  PYTHON="$_VENV_PY"
elif command -v python3 >/dev/null 2>&1; then
  PYTHON="python3"
else
  echo "compare-regression-runs.sh: python3 not found (run: python3 -m venv .venv in plugin root)" >&2
  exit 1
fi

"$PYTHON" "$SCRIPT_DIR/lib/compare_regression_runs.py" "$summary_a" "$summary_b" "$out_path"

